//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EksamenDatabaseEntities : DbContext
    {
        public EksamenDatabaseEntities()
            : base("name=EksamenDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Køber> Køber { get; set; }
        public virtual DbSet<Købstilbud> Købstilbud { get; set; }
        public virtual DbSet<Salgsudbud> Salgsudbuds { get; set; }
    }
}
