//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Købstilbud
    {
        public int KøbstilbudId { get; set; }
        public decimal pris { get; set; }
        public int køberId { get; set; }
        public int salgsudbudId { get; set; }
    
        public virtual Køber Køber { get; set; }
        public virtual Salgsudbud Salgsudbud { get; set; }
    }
}
